server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://db:5432/ticketsdb
    username: postgres
    password: tu_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  application:
    name: microservicio-tickets
