version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dgtovar2311
      POSTGRES_DB: ticketsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  tickets:
    build: .
    container_name: microservicio-tickets
    ports:
      - "8082:8082"
    depends_on:
      - db
      - rabbitmq

volumes:
  pgdata:
